# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NBQTsnmm5zHjZpnEkWsRFPw=,iv:3BKAHru0gYcVJkxzJHTosB26Wdeq181H1VyNQyYEwLM=,tag:Ue2kI1YgB2hR3lMEX2uwXQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nutJX0CDCoUxyIs0yUlylWxC63Q37G4=,iv:5xrT5d9uDkm16breel7A40rhrqlhRddP17j2qqpebFI=,tag:iczHsYsP3Wx4eaKKy0nKFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-19T16:31:32Z"
    mac: ENC[AES256_GCM,data:v77sJvLuw+k033ML/eZfSBxSbuI7M1uNoWkY7XSdfBz6rBQqL/StSa/zRbXIZZZ4Fh3nF7lnBWiBn/ZJQfT4r1iClnN5elgxTgzkA3HM3qF0Kg5fQiZ52jm+fzJ/8JhI1HTljMEXogLUSKpBq7G03Hn6+HQjCKxwk+EVra1ugOk=,iv:RyyYkN4LcofUUVOovxPcwaMHhU6fGEkX2J3nRdN7R8U=,tag:Q1WgBvpFY5VYGPhDaxf+jw==,type:str]
    pgp:
        - created_at: "2021-07-19T16:31:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA769DrvHJKdPAQ//YJn3t7KqBYoRPpSibSlEVJTX5vnKO7l97gL636SIbUlq
            7hI/CJiErS5wW0nnJd+qBowwOP5FbS9Fnt0YEDf1LkQphSnDibxRnaqzQF9VzQ5a
            XQTxisVr+i6hWnIS8cRQEF5Oi9L3XLMpnkCBoyden3owmIEOxLMtP3rh5El1H/kM
            bsYpA+biWVuKs4imOODlk1ecPikddkotPwh94yxs1SfbfQ1YJk2kGnHT5ROOM1ti
            cTDgWHfPiXM7+m0AFgYj0e52oGNqoRIiFyaAqm2nkFN0CMXeBh1obTlCfhgu6b0b
            ddcL9YLyX3RlS94FWZ6GHGTxJHfgvncRX/edajRKt9zQ9EkITe43F1D2JszeFB8N
            K20t/7IjpvI1DDtrjjOv26hWlNWS6Rdta7xPuzwmOvEbsL4Ca+g0Wnq7tM2Eyp6A
            csGBPUizXPwrB7CcvgMrkttc1H23dCc51k2eEzPch/ctFQj/H/HxnwPb7lxUSdIz
            RtJXFAhX/QUYTD+LM0PMLK+zAKxNO0l/SRtp3WMPt+x/YuYn+WJg8uSuK29jqhBc
            vHqNdViTgPknAwgFhApCs2Yd8zKAQv1FJtN6PLL4uoqkiQlEHFFIGtbTr7NTfx9T
            /swEJ39U6azx0XLWob5J6LelHZsWcak20mKF/Eld72EGUQ96VgGQkA7ZcR5G3mnS
            XgHY6zPw8Zjw97vd9WiFmieMGnezLcUVTk7+oZ9p8OoZqnm4a3Qhtdru6N4BmWop
            wK1kvr24ptZgAQmTsz3DgpYm+mj+VNQ4pEcynM5VwT9YsqKMOpfq1HCp4XqsN10=
            =eh6z
            -----END PGP MESSAGE-----
          fp: 4B6C89CA06C97A00FE41A813DBDB617B8D44C0C9
        - created_at: "2021-07-19T16:31:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA93dXafOjmLfARAArIsOUcWkYzpibb17Lhczh5JpWgcZ9VLYXx9z8332sVIY
            ZJzFs73oYtT1e00QosKrnPNc8kMho5UG9te+UsjNSE7sbwdISHkNQ0LCS6Or1vUG
            u2AaJGedmV+xEPtY3tWGfT0nAEB2H4lB7sIRPwzxV/aL4hT61LiHEmyge6eDtXeI
            gJXqZKH8XdxjOH2j9OAYP9/Out578H9lC8RTDg8ncSIVPY38IGRiFWAVRgnk4xWF
            cM2Eau+JmE49JF0YneUUcMf/3W/1YG/tMqekeN7/3x9RvzpV0WzNh31DB5B5Qbb1
            Hj/ejRfSOcHoK6DR19VX5y31zyKcvh0A3eeQLfKfDgw2XFADGudURaEeo6dJh9MU
            kcKBOe8vC6phl6tuUX6fS8axtJdHuvZzVUyA8IkPsthOxAZioIdZ/9gcAsS1PbWm
            KHXkHvY/jzDpReEzIoNrO+NR0uiysX2gC1vjGsEFKuHZ+kCkfHr5/XcTetSbEOk+
            ViRxs5Ctm1c71Kqi2YorNTBuIJlnxPW1VjNzrwhktZZ01Bxf9p4nxLFEm2PORO5B
            Hf7IHjVSR6nlVU02yFfi7u4ggTS+Kw7ww7u+TvVWd2B3QIYpxKOvkwg3Wwtkqjvt
            IDN3b5l9RNFiqyuNSB++YX4nGXwjjBnS12KxvmXYhdJAySfuTPBl9oxS/pRm+nLS
            XgHSZh5u9c1lTpcnA2/dYoppgilOBqumypqzkdSRX3eEMufjEhL5PP5hQLKzPv0I
            4VB+g1PLqjm7IAPeTpW09ylT0681n/M3u8khPs3divh64BGpS+FpdXsy3e696qk=
            =MThi
            -----END PGP MESSAGE-----
          fp: 477E04B93D4A4B7CB903A7A54370F759E58AB978
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
